# Generated by Django 4.2.21 on 2025-06-02 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ipam", "0051_added_optional_vrf_relationship_to_vdc"),
        ("nautobot_dns_models", "0002_srvrecordmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aaaarecordmodel",
            name="address",
            field=models.ForeignKey(
                limit_choices_to={"ip_version": 6}, on_delete=django.db.models.deletion.CASCADE, to="ipam.ipaddress"
            ),
        ),
        migrations.AlterField(
            model_name="arecordmodel",
            name="address",
            field=models.ForeignKey(
                limit_choices_to={"ip_version": 4}, on_delete=django.db.models.deletion.CASCADE, to="ipam.ipaddress"
            ),
        ),
    ]
