# Generated by Django 3.2.25 on 2024-08-01 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nautobot_dns_models", "0002_auto_20240731_2216"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dnszonemodel",
            name="slug",
        ),
    ]
