# Generated by Django 4.2.25 on 2025-10-09 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ipam", "0053_alter_vrfdeviceassignment_options_and_more"),
        ("nautobot_dns_models", "0004_rename_aaaarecordmodel_aaaarecord_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="aaaarecord",
            old_name="address",
            new_name="ipaddress",
        ),
        migrations.RenameField(
            model_name="arecord",
            old_name="address",
            new_name="ipaddress",
        ),
        migrations.AlterUniqueTogether(
            name="aaaarecord",
            unique_together={("name", "ipaddress", "zone")},
        ),
        migrations.AlterUniqueTogether(
            name="arecord",
            unique_together={("name", "ipaddress", "zone")},
        ),
    ]
