# Generated by Django 3.2.25 on 2024-08-01 11:36

import django.db.models.deletion
import nautobot.core.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_dns_models", "0004_auto_20240801_1129"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aaaarecordmodel",
            name="zone",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="aaaa_records",
                to="nautobot_dns_models.dnszonemodel",
            ),
        ),
        migrations.AlterField(
            model_name="arecordmodel",
            name="zone",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="a_records",
                to="nautobot_dns_models.dnszonemodel",
            ),
        ),
        migrations.AlterField(
            model_name="cnamerecordmodel",
            name="zone",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cname_records",
                to="nautobot_dns_models.dnszonemodel",
            ),
        ),
        migrations.AlterField(
            model_name="mxrecordmodel",
            name="zone",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mx_records",
                to="nautobot_dns_models.dnszonemodel",
            ),
        ),
        migrations.AlterField(
            model_name="nsrecordmodel",
            name="zone",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ns_records",
                to="nautobot_dns_models.dnszonemodel",
            ),
        ),
        migrations.AlterField(
            model_name="ptrrecordmodel",
            name="zone",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ptr_records",
                to="nautobot_dns_models.dnszonemodel",
            ),
        ),
        migrations.AlterField(
            model_name="txtrecordmodel",
            name="zone",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="txt_records",
                to="nautobot_dns_models.dnszonemodel",
            ),
        ),
    ]
