# Generated by Django 4.2.25 on 2025-10-10 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0009_update_all_charfields_max_length_to_255'),
        ('nautobot_dns_models', '0005_rename_address_aaaarecord_ipaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aaaarecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='arecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='cnamerecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='dnszone',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='mxrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='nsrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='ptrrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='srvrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='txtrecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)ss', to='tenancy.tenant'),
        ),
    ]
