# Generated by Django 4.2.26 on 2026-02-17 18:35

import uuid

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0132_approval_workflow_seed_data"),
        ("nautobot_dns_models", "0006_rename_address_aaaarecord_ip_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnszone",
            name="auto_renewal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dnszone",
            name="dnssec_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dnszone",
            name="expiration_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dnszone",
            name="privacy_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dnszone",
            name="registry_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dnszone",
            name="renewal_term_months",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(1200),
                ],
            ),
        ),
        migrations.AddField(
            model_name="dnszone",
            name="transfer_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dnszone",
            name="website_forwarding_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="DNSRegistrar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("account_number", models.CharField(blank=True, max_length=100)),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "DNS Registrar",
                "verbose_name_plural": "DNS Registrars",
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="dnszone",
            name="dns_registrar",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nautobot_dns_models.dnsregistrar",
            ),
        ),
    ]
