# Generated by Django 4.2.29 on 2026-03-16 11:54

import uuid

import django.core.serializers.json
import django.core.validators
import django.db.models.deletion
import nautobot.core.models.fields
import nautobot.extras.models.mixins
import nautobot.extras.models.statuses
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("extras", "0132_approval_workflow_seed_data"),
        ("nautobot_dns_models", "0006_rename_address_aaaarecord_ip_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DNSRegistrar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("account_number", models.CharField(blank=True, max_length=100)),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "DNS Registrar",
                "verbose_name_plural": "DNS Registrars",
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="DNSRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "_custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder),
                ),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("auto_renewal", models.BooleanField(default=False)),
                ("registry_locked", models.BooleanField(default=False)),
                ("transfer_locked", models.BooleanField(default=False)),
                ("privacy_enabled", models.BooleanField(default=False)),
                ("website_forwarding_enabled", models.BooleanField(default=False)),
                (
                    "renewal_term_months",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1200),
                        ],
                    ),
                ),
                ("dnssec_enabled", models.BooleanField(default=False)),
                (
                    "dns_registrar",
                    nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                        on_delete=django.db.models.deletion.PROTECT, to="nautobot_dns_models.dnsregistrar"
                    ),
                ),
                (
                    "dns_zone",
                    nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                        on_delete=django.db.models.deletion.PROTECT, to="nautobot_dns_models.dnszone"
                    ),
                ),
                (
                    "status",
                    nautobot.extras.models.statuses.StatusField(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="extras.status"
                    ),
                ),
                ("tags", nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "verbose_name": "DNS Registration",
                "verbose_name_plural": "DNS Registrations",
                "unique_together": {("dns_registrar", "dns_zone")},
            },
            bases=(
                nautobot.extras.models.mixins.DataComplianceModelMixin,
                nautobot.extras.models.mixins.DynamicGroupMixin,
                nautobot.extras.models.mixins.NotesMixin,
                models.Model,
            ),
        ),
    ]
