# Generated by Django 4.2.26 on 2026-02-24 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nautobot_dns_models', '0007_dnsregistrar_dnsregistration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dnsregistration',
            unique_together={('dns_registrar', 'dns_zone')},
        ),
    ]
