# Generated by Django 4.2.29 on 2026-05-08 14:41

from django.db import migrations, models


def set_default_auto_create_ptr(apps, schema_editor):
    """Set auto_create_ptr=False on existing DNSZones (preserves prior behavior; opt-in per zone)."""
    DNSZone = apps.get_model("nautobot_dns_models", "DNSZone")
    DNSZone.objects.filter(auto_create_ptr__isnull=True).update(auto_create_ptr=False)


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_dns_models", "0007_dnsregistrar_dnsregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnszone",
            name="auto_create_ptr",
            field=models.BooleanField(null=True),
        ),
        migrations.RunPython(set_default_auto_create_ptr, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="dnszone",
            name="auto_create_ptr",
            field=models.BooleanField(default=False),
        ),
    ]
