# Generated by Django 5.2.16 on 2026-07-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_dns_models", "0008_dnszone_auto_create_ptr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dnszone",
            name="soa_rname",
            field=models.CharField(max_length=254),
        ),
    ]
