# Generated by Django 4.2.29 on 2026-05-18 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_dns_models", "0008_dnszone_auto_create_ptr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dnszone",
            name="soa_serial",
            field=models.PositiveBigIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(4294967295)]
            ),
        ),
    ]
