# Generated by Django 5.2.16 on 2026-07-25 19:20

from django.db import migrations, models


def set_default_enabled(apps, schema_editor):
    """Set enabled=True on existing DNSZones (preserves prior behavior; zones remain active)."""
    DNSZone = apps.get_model("nautobot_dns_models", "DNSZone")
    DNSZone.objects.filter(enabled__isnull=True).update(enabled=True)


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_dns_models", "0009_alter_aaaarecord__ttl_alter_arecord__ttl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnszone",
            name="enabled",
            field=models.BooleanField(null=True),
        ),
        migrations.RunPython(set_default_enabled, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="dnszone",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
