# Generated by Django 5.2.15 on 2026-08-12 09:29

from django.db import migrations, models


def set_default_enabled(apps, schema_editor):
    """Set enabled=True on existing DNS models (preserves prior behavior; zones remain active)."""
    DNSZone = apps.get_model("nautobot_dns_models", "DNSZone")
    DNSZone.objects.filter(enabled__isnull=True).update(enabled=True)
    ARecord = apps.get_model("nautobot_dns_models", "ARecord")
    ARecord.objects.filter(enabled__isnull=True).update(enabled=True)
    AAAARecord = apps.get_model("nautobot_dns_models", "AAAARecord")
    AAAARecord.objects.filter(enabled__isnull=True).update(enabled=True)
    CNAMERecord = apps.get_model("nautobot_dns_models", "CNAMERecord")
    CNAMERecord.objects.filter(enabled__isnull=True).update(enabled=True)
    MXRecord = apps.get_model("nautobot_dns_models", "MXRecord")
    MXRecord.objects.filter(enabled__isnull=True).update(enabled=True)
    NSRecord = apps.get_model("nautobot_dns_models", "NSRecord")
    NSRecord.objects.filter(enabled__isnull=True).update(enabled=True)
    PTRRecord = apps.get_model("nautobot_dns_models", "PTRRecord")
    PTRRecord.objects.filter(enabled__isnull=True).update(enabled=True)
    SRVRecord = apps.get_model("nautobot_dns_models", "SRVRecord")
    SRVRecord.objects.filter(enabled__isnull=True).update(enabled=True)
    TXTRecord = apps.get_model("nautobot_dns_models", "TXTRecord")
    TXTRecord.objects.filter(enabled__isnull=True).update(enabled=True)


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_dns_models", "0009_alter_aaaarecord__ttl_alter_arecord__ttl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aaaarecord",
            name="enabled",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="arecord",
            name="enabled",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="cnamerecord",
            name="enabled",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="dnszone",
            name="enabled",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="mxrecord",
            name="enabled",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="nsrecord",
            name="enabled",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="ptrrecord",
            name="enabled",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="srvrecord",
            name="enabled",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="txtrecord",
            name="enabled",
            field=models.BooleanField(null=True),
        ),
        migrations.RunPython(set_default_enabled, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="aaaarecord",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="arecord",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="cnamerecord",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="dnszone",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="mxrecord",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="nsrecord",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="ptrrecord",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="srvrecord",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="txtrecord",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
