# Generated by Django 5.2.16 on 2026-07-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_dns_models", "0009_alter_aaaarecord__ttl_alter_arecord__ttl_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dnszone",
            name="soa_rname",
            field=models.CharField(max_length=254),
        ),
    ]
