# Generated by Django 5.2.16 on 2026-08-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nautobot_dns_models", "0010_alter_dnszone_soa_rname"),
    ]

    # `enabled` is added to every DNSModel subclass with a non-null default, so existing
    # objects keep the prior behavior of being eligible for publication.
    operations = [
        migrations.AddField(
            model_name="aaaarecord",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="arecord",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cnamerecord",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="dnszone",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="mxrecord",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="nsrecord",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ptrrecord",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="srvrecord",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="txtrecord",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
